// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu_NfAuUdg_EJsjG9MsITEMKXXi_V-yBQ',
    appId: '1:294945150333:web:353d0218b05c2d6d8d6814',
    messagingSenderId: '294945150333',
    projectId: 'smart-bin-d45a1',
    authDomain: 'smart-bin-d45a1.firebaseapp.com',
    storageBucket: 'smart-bin-d45a1.firebasestorage.app',
    measurementId: 'G-TFXQHTD34V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU6c9MPuOL-hVrXr6QOGmgTVQi_HJQgtE',
    appId: '1:294945150333:android:402158f1c19a2f978d6814',
    messagingSenderId: '294945150333',
    projectId: 'smart-bin-d45a1',
    storageBucket: 'smart-bin-d45a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR3oJrQxGUPjb_g6b4wzKrzm5pPR9QxJk',
    appId: '1:294945150333:ios:5c041f46918013ad8d6814',
    messagingSenderId: '294945150333',
    projectId: 'smart-bin-d45a1',
    storageBucket: 'smart-bin-d45a1.firebasestorage.app',
    iosBundleId: 'com.zion.smartbin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR3oJrQxGUPjb_g6b4wzKrzm5pPR9QxJk',
    appId: '1:294945150333:ios:93b58821421358348d6814',
    messagingSenderId: '294945150333',
    projectId: 'smart-bin-d45a1',
    storageBucket: 'smart-bin-d45a1.firebasestorage.app',
    iosBundleId: 'com.example.smartBin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu_NfAuUdg_EJsjG9MsITEMKXXi_V-yBQ',
    appId: '1:294945150333:web:b65cc084024663a18d6814',
    messagingSenderId: '294945150333',
    projectId: 'smart-bin-d45a1',
    authDomain: 'smart-bin-d45a1.firebaseapp.com',
    storageBucket: 'smart-bin-d45a1.firebasestorage.app',
    measurementId: 'G-01LESH1P53',
  );
}
